const prefix = "THREAD_REPOSITORY_ERROR";

export const THREAD_REPOSITORY_ERROR = {
  METHOD_NOT_IMPLEMENTED: `${prefix}.METHOD_NOT_IMPLEMENTED`,
  THREAD_NOT_FOUND: `${prefix}.THREAD_NOT_FOUND`,
};

export const THREAD_REPOSITORY_ERROR_MESSAGE = {
  THREAD_NOT_FOUND: "the thread is not found",
};
