const prefix = "THREAD_DETAIL_ERROR";

export const THREAD_DETAIL_ERROR = {
  THREAD: {
    MISSING_PROPERTY: `${prefix}.THREAD.MISSING_PROPERTY`,
    INVALID_DATA_TYPE: `${prefix}.THREAD.INVALID_DATA_TYPE`,
  },
  COMMENT: {
    MISSING_PROPERTY: `${prefix}.COMMENT.MISSING_PROPERTY`,
    INVALID_DATA_TYPE: `${prefix}.COMMENT.INVALID_DATA_TYPE`,
  },
  REPLY: {
    MISSING_PROPERTY: `${prefix}.REPLY.MISSING_PROPERTY`,
    INVALID_DATA_TYPE: `${prefix}.REPLY.INVALID_DATA_TYPE`,
  },
};
