const prefix = "COMMENT_THREAD_CONTEXT_ERROR";

export const COMMENT_LOCATOR_CONTEXT_ERROR = {
  MISSING_PROPERTY: `${prefix}.MISSING_PROPERTY`,
  INVALID_DATA_TYPE: `${prefix}.INVALID_DATA_TYPE`,
};
