const prefix = "GET_THREAD_DETAIL_USE_CASE_ERROR";

export const GET_THREAD_DETAIL_USE_CASE_ERROR = {
  MISSING_PROPERTY: `${prefix}.MISSING_PROPERTY`,
  INVALID_DATA_TYPE: `${prefix}.INVALID_DATA_TYPE`,
};
