const prefix = "SOFT_DELETE_REPLY_USE_CASE_ERROR";

export const SOFT_DELETE_REPLY_USE_CASE_ERROR = {
  MISSING_PROPERTY: `${prefix}.MISSING_PROPERTY`,
  INVALID_DATA_TYPE: `${prefix}.INVALID_DATA_TYPE`,
};
