const prefix = "AUTHENTICATION_TOKEN_MANAGER_ERROR";

export const AUTHENTICATION_TOKEN_MANAGER_ERROR = {
  METHOD_NOT_IMPLEMENTED: `${prefix}.METHOD_NOT_IMPLEMENTED`,
  INVALID_REFRESH_TOKEN: `${prefix}.INVALID_REFRESH_TOKEN`,
};

export const AUTHENTICATION_TOKEN_MANAGER_ERROR_MESSAGE = {
  INVALID_REFRESH_TOKEN: "refresh token tidak valid",
};
