const prefix = "PASSWORD_HASH_ERROR";

export const PASSWORD_HASH_ERROR = {
  METHOD_NOT_IMPLEMENTED: `${prefix}.METHOD_NOT_IMPLEMENTED`,
  INCORRECT_CREDENTIALS: `${prefix}.INCORRECT_CREDENTIALS`,
};

export const PASSWORD_HASH_ERROR_MESSAGE = {
  INCORRECT_CREDENTIALS: "incorrect credentials",
};
