name: Continuous Deployment

on:
  push:
    branches: reverse-proxy

jobs:
  deploy-reverse-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Scalingo
        uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          app-name: ${{ vars.SCALINGO_APP_NAME }}
          known-host: ${{ vars.SCALINGO_KNOWN_HOST }}
